FROM public.ecr.aws/lambda/python:3.9

# Install dependencies
RUN yum install -y \
    gcc \
    cmake \
    make \
    libjpeg-turbo-devel \
    libpng-devel \
    libtiff-devel \
    libavcodec-devel \
    libavformat-devel \
    libswscale-devel \
    libv4l-devel \
    libxvidcore-devel \
    libx264-devel \
    gtk2-devel \
    atlas-devel \
    && yum clean all

# Install Python dependencies
RUN pip install easyocr numpy boto3

# Copy the rest of the application code
COPY . .

# Build and install OpenCV with only the necessary modules
RUN git clone --depth 1 --branch 4.5.3 https://github.com/opencv/opencv.git && \
    mkdir /opencv/build && \
    cd /opencv/build && \
    cmake -D CMAKE_BUILD_TYPE=RELEASE \
          -D CMAKE_INSTALL_PREFIX=/usr/local \
          -D BUILD_EXAMPLES=OFF \
          -D BUILD_opencv_python3=ON \
          -D BUILD_opencv_python2=OFF \
          -D BUILD_opencv_java=OFF \
          -D BUILD_opencv_js=OFF \
          -D BUILD_opencv_ts=OFF \
          -D BUILD_opencv_world=OFF \
          -D BUILD_opencv_apps=OFF \
          -D BUILD_opencv_dnn=OFF \
          -D BUILD_opencv_ml=OFF \
          -D BUILD_opencv_objdetect=OFF \
          -D BUILD_opencv_photo=OFF \
          -D BUILD_opencv_stitching=OFF \
          -D BUILD_opencv_video=OFF \
          -D BUILD_opencv_videoio=OFF \
          -D BUILD_opencv_videostab=OFF \
          -D BUILD_opencv_highgui=OFF \
          -D BUILD_opencv_imgcodecs=ON \
          -D BUILD_opencv_imgproc=ON \
          -D BUILD_opencv_core=ON \
          .. && \
    make -j$(nproc) && \
    make install && \
    ldconfig && \
    cd / && \
    rm -rf /opencv

# Set the CMD to your handler (could be any file in your package)
CMD ["ovalNameDetection.main"]