FROM public.ecr.aws/lambda/python:3.10

RUN yum update -y && \
    yum -y install \
    g++ \
    make \
    cmake \
    unzip \
    libcurl4-openssl-dev

RUN yum -y install \
    build-essential \
    cmake \
    gfortran \
    git \
    wget \
    curl \
    ffmpeg \
    libsm6 \
    libxext6 \
    graphicsmagick \
    libgraphicsmagick1-dev \
    libatlas-base-dev \
    libavcodec-dev \
    libavformat-dev \
    libgtk2.0-dev \
    libjpeg-dev \
    liblapack-dev \
    libswscale-dev \
    pkg-config \
    python3-dev \
    python3-numpy \
    software-properties-common \
    zip \
    && yum clean all && rm -rf /tmp/* /var/tmp/*

RUN pip install easyocr opencv-python-headless numpy boto3

COPY lambda_function.py ./

CMD ["lambda_function.lambda_handler"]