name: "Compile LaTeX Document"

on:
  push:
    branches:
      - test-build-pdf
    paths:
      - "docs/**/*.tex"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Cache TeX Live installation
      - name: Cache TeX Live
        uses: actions/cache@v4
        with:
          path: |
            /usr/local/texlive
            /usr/share/texlive
            ~/.texlive
          key: texlive-2024-${{ runner.os }}-latexmk
          restore-keys: |
            texlive-

      # Install TeX Live and latexmk if cache is not available
      - name: Install TeX Live and latexmk
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install texlive-latex-extra texlive-science latexmk

      # Checkout repository (using default GitHub token)
      - name: Checkout repository
        uses: actions/checkout@v4

      # Get changed .tex files
      - name: Get changed .tex files
        id: changed-tex-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            **/*.tex
          diff_relative: true
          files_ignore: |
            docs/Comments.tex
            docs/Common.tex
            docs/Reflection.tex

      # Build LaTeX files
      - name: Build changed tex files
        if: steps.changed-tex-files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-tex-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            folder=$(dirname "$file")
            filename=$(basename "$file")
            echo "Building $filename in $folder"
            cd "$folder"
            latexmk -pdf -interaction=nonstopmode "$filename" || echo "Failed to build $filename" >&2
            latexmk -c || echo "Failed to clean up auxiliary files for $filename" >&2
            cd -
          done

      # Commit the generated PDF back to the repository
      - name: Commit & Push changes
        if: steps.changed-tex-files.outputs.any_changed == 'true'
        uses: EndBug/add-and-commit@v9
        with:
          add: --force docs/**/*.pdf
          author_name: "GitHub Action"
          author_email: "action@github.com"
          message: "Add compiled PDF"