name: Code Check
on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
  group: ${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: ⬣ ESLint, ʦ TypeScript, 💅 Prettier, and 🃏 Test
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2

      - name: 🤌 Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: "**/package-lock.json"

      - name: 📥 Download deps
        run: pnpm install --frozen-lockfile
        working-directory: ./client
      - name: 🔬 Lint
        run: pnpm run lint
        working-directory: ./client

      - name: 🔎 Type check
        run: pnpm run typecheck
        working-directory: ./client

      - name: 💅 Prettier check
        run: pnpm run format:check
        working-directory: ./client

      - name: 🃏 Run Vitest
        run: pnpm run test
        working-directory: ./client
